### ISSUE TITLE
Adding new Image Sizes doesn't work anymore

### ISSUE THREAD

**Issue by rgbfreak** [Rahe/Simple-image-sizes#27]
If I click on this button, nothing happens:
![simple-image-resize1](https://cloud.githubusercontent.com/assets/5921023/7515064/cfa7ede2-f4c3-11e4-850f-da6db9ee22b6.JPG)

Here are some PHP Errors:
![simple-image-resize2](https://cloud.githubusercontent.com/assets/5921023/7515065/d55f29e4-f4c3-11e4-9193-23d26e6d31a4.JPG)

**Comment by Rahe** [comment]
Hi !
Thank you for the report :).

These errors are on the previous version of the plugin, have you the last one installed ?

**Comment by rgbfreak** [comment]
Hi Rahe :)

I have installed version 3.0.4

Here is a screenshot from the database entry (maybe it helps you):
![simple-image-resize3](https://cloud.githubusercontent.com/assets/5921023/7519568/50cbc19c-f4e1-11e4-8454-038a1813a171.JPG)

serialized array:
a:4:{s:10:"660-double";a:6:{s:6:"custom";s:1:"1";s:1:"w";s:3:"660";s:1:"h";s:3:"660";s:1:"n";s:22:"2/3 Breit, quadratisch";s:1:"c";s:13:"center_center";s:1:"s";s:1:"1";}s:12:"490-angebote";a:6:{s:6:"custom";s:1:"1";s:1:"w";s:3:"490";s:1:"h";s:3:"245";s:1:"n";s:18:"Angebot Übersicht";s:1:"c";s:13:"center_center";s:1:"s";s:1:"1";}s:8:"640-high";a:6:{s:6:"custom";s:1:"1";s:1:"w";s:3:"640";s:1:"h";s:1:"0";s:1:"n";s:14:"Angebot Detail";s:1:"c";s:1:"0";s:1:"s";s:1:"1";}s:8:"660-wide";a:6:{s:6:"custom";s:1:"1";s:1:"w";s:3:"660";s:1:"h";s:3:"320";s:1:"n";s:22:"2/3 Breit, Breitformat";s:1:"c";s:13:"center_center";s:1:"s";s:1:"1";}}

unserialized array:
```php
array(4) {
  ["660-double"]=>
  array(6) {
    ["custom"]=>
    string(1) "1"
    ["w"]=>
    string(3) "660"
    ["h"]=>
    string(3) "660"
    ["n"]=>
    string(22) "2/3 Breit, quadratisch"
    ["c"]=>
    string(13) "center_center"
    ["s"]=>
    string(1) "1"
  }
  ["490-angebote"]=>
  array(6) {
    ["custom"]=>
    string(1) "1"
    ["w"]=>
    string(3) "490"
    ["h"]=>
    string(3) "245"
    ["n"]=>
    string(18) "Angebot Ãœbersicht"
    ["c"]=>
    string(13) "center_center"
    ["s"]=>
    string(1) "1"
  }
  ["640-high"]=>
  array(6) {
    ["custom"]=>
    string(1) "1"
    ["w"]=>
    string(3) "640"
    ["h"]=>
    string(1) "0"
    ["n"]=>
    string(14) "Angebot Detail"
    ["c"]=>
    string(1) "0"
    ["s"]=>
    string(1) "1"
  }
  ["660-wide"]=>
  array(6) {
    ["custom"]=>
    string(1) "1"
    ["w"]=>
    string(3) "660"
    ["h"]=>
    string(3) "320"
    ["n"]=>
    string(22) "2/3 Breit, Breitformat"
    ["c"]=>
    string(13) "center_center"
    ["s"]=>
    string(1) "1"
  }
}
```

**Comment by underblob** [comment]
Hi Rahe, looks like 3.0.5 has not been published to the WordPress plugin directory yet:
https://wordpress.org/plugins/simple-image-sizes/

**Comment by Rahe** [comment]
Hoooo i forgot tout publish it on WordPress....
I will do this as soon as possible.
Did the 3.0.5 solve this ?

**Comment by underblob** [comment]
Yea, 3.0.5 works great. Great job on this plugin!

**Comment by Rahe** [comment]
Thank you !
