### ISSUE TITLE
Regenerating images not working and on Settings -> Media page is showing PHP Warning.

### ISSUE THREAD

**Issue by DzeryCZ** [Rahe/Simple-image-sizes#28]
Hello,

I have the newest version of Simple Image Sizer plguin (3.0.4), but If I enter Settings -> Media page, so I'm getting this PHP Warning: 

    Warning: Illegal offset type in isset or empty in ....plugins\simple-image-sizes\classes\admin\main.php on line 200

And Regenerate of thumbnails isn't working. Do you have any fix for this issue?

Many thanks.

**Comment by Rahe** [comment]
Hi,

Have yout try the 3.0.5 ?


Rahe

**Comment by DzeryCZ** [comment]
Unfortunately there is still showing PHP Warning, however Regeneration of thumbnails now works.

THX
