### ISSUE TITLE
Warning: Illegal offset type in isset or empty in simple-image-sizes/classes/admin/main.php on line 200

### ISSUE THREAD

**Issue by haleeben** [Rahe/Simple-image-sizes#29]
Hi 

I'm on version 3.0.5
WP version 4.2.2 

I have created a new image size but if I select a crop position other than "No" I get the Illegal offset type error. Then if I save, no crop position shows.

![imagecrop](https://cloud.githubusercontent.com/assets/629232/7790563/621d99c8-02d0-11e5-8efa-c7e98f17137a.png)

**Comment by gigi69** [comment]
I'm getting the same error message. This is what is on line 200:

return isset( $crops[ $crop_position ] );

**Comment by Rahe** [comment]
Thank you for the report, 

I'm working on this problem... The version 3.0.5 was made to fix this problem...

Meanwhile you can use the 3.0.3 version.

**Comment by gigi69** [comment]
Thank you! The workaround I found is to NOT press "save" after I add the new thumbnail size. The error message is still there, but I able to regenerate and use the new thumbnail properly in pages/posts.

Great plugin! Many thanks.

**Comment by Rahe** [comment]
Hello,

Is the 3.0.6 working ?

**Comment by haleeben** [comment]
Hi Rahe

Yes, it is working correctly now.

Thanks for the fix and this awesome plugin :)

**Comment by Rahe** [comment]
Great ! :)
You're welcome  !
