### ISSUE TITLE
Conflict with WP Simple Paypal Shopping Cart plugin- showing warning/error...

### ISSUE THREAD

**Issue by crzyhrse** [Rahe/Simple-image-sizes#30]
The long version is in this support thread- https://wordpress.org/support/topic/error-warning-7?

The shorter version is that this error is appearing on the Media settings page between "Select which post type source thumbnails you want to rebuild:" and the section where the selections are made -

Warning: array_key_exists() expects parameter 2 to be array, null given in /home/purelialch/public_html/wp-content/plugins/simple-image-sizes/templates/options-media.php on line 88

On a new WP install in its own cPanel with 2015 as the theme and only the WP Simple PayPal Shopping Cart and Simple Image Sizes plugins activated, no other plugins activated, the warning/error is there...  When WP Simple PayPal Shopping Cart is deactivated the error goes away, when reactivated the warning reappears...

On a post about this in the WP Simple PayPal Shopping Cart support forum one of the plugin's authors is saying they cannot do anything about it...

**Comment by Rahe** [comment]
Hi,

Thqnk you for the report, it seems the other plugin us making the array of available images a null element..
I will add a condition tout check if the returned value is an array before calling array_key_exists.

**Comment by crzyhrse** [comment]
And thank you for getting back with this so quickly...  If you want me to try it out when it is ready let me know...

Kind regards...

**Comment by Rahe** [comment]
Hi !

The version 3.0.7 normally fix this problem, let me know :)

**Comment by crzyhrse** [comment]
It appears to be fixed...  :-)

Thank you very much for being so prompt...

**Comment by Rahe** [comment]
You're welcome :)
