### ISSUE TITLE
Changing Cropping Settings Doesn't Persist Upon Save v3.0.8

### ISSUE THREAD

**Issue by cranappras** [Rahe/Simple-image-sizes#31]
Since the most recent update, I am unable to set the cropping settings to "No." I can switch the thumbnail size setting to No cropping and then update, but as soon as I hit Save, the cropping setting reverts back to "Yes." This was working fine before I updated to v3.0.8.

**Comment by Rahe** [comment]
Hi !

If you try with the last master zip, is this still not working ?
