### ISSUE TITLE
nothing happend!

### ISSUE THREAD

**Issue by selftripsdotru** [Rahe/Simple-image-sizes#32]
I press regenerate thumbnails and
Regenerating 1 of 7947
End time calculated : Calculating...  and that all
or
just nothing at all!!!
what i may to do to fix this problem?

**Comment by Rahe** [comment]
Hi,

It seems you have a PHP error on AJAX call, can you copy paste the ajax return ?

**Comment by selftripsdotru** [comment]
support tell me this pluging doesnt work with "accelerater php"  

13.10.2015, 19:36, "Nicolas Juen" <notifications@github.com>:

**Comment by Rahe** [comment]
I'm only using the WordPress API for this.
Can you copy/paste me the errors ?

**Comment by selftripsdotru** [comment]
i cant, support checked. 

APC accelerator

**Comment by Rahe** [comment]
I have tested my plugin with APC and other opcode cache and haven't had any problems.
Without any error I cannot help you, sorry.
