### ISSUE TITLE
How can I make generated image name to use the public name provided by me.

### ISSUE THREAD

**Issue by kala725** [Rahe/Simple-image-sizes#33]
How can I make generated image name to use the public name provided by me. Currently it is taking the width*height.

Eg: I am resizing the image : simple-image.jpg to 1024*768 (md)

The image is resizing with name simple-image-1024*768.jpg

what I want is : simple-image-md.jpg.

How I can do that ??

**Comment by kala725** [comment]
You  can do it by passing the size as prefix in the wp-includes/class-wp-image-editor-gd.php under multi_resize() function. 


Change the below line in multi_resize()  function in the class-wp-image-editor-gd.php : 
$this->_save( $image);

to:
$this->_save( $image,null,null,$size );

 AND modify the _save() function as :

protected function _save( $image, $filename = null, $mime_type = null, $suffix = null ) {
		list( $filename, $extension, $mime_type ) = $this->get_output_format( $filename, $mime_type );

		if ( ! $filename )
			$filename = $this->generate_filename( $suffix, null, $extension );

**Comment by Rahe** [comment]
Hi,

Don't change the core of WordPress in any way, this is dangerous and at the next version of WordPress your modifications will be erased.

Maybe there is a filter when the path is generated.

**Comment by Rahe** [comment]
Look a WP Thumb plugin, they are changing the path to the image sizes generated.
