### ISSUE TITLE
Can't disable button "Regenerate Image Sizes" in wp-admin/post-new.php

### ISSUE THREAD

**Issue by eduardoarandah** [Rahe/Simple-image-sizes#35]
This plugin generates a big button "Regenerate Image Sizes" next to "set featured image"
![button](https://cloud.githubusercontent.com/assets/4065733/14925544/93324542-0e0d-11e6-84f3-cb89f4b32e15.jpg)

This button is bigger and more visible than the link "set featured image" and causes confusion on the final user. 

I think it should be gone, or hidden by default. Image regeneration is something useful only during development, must not be available to end user.

**Comment by eduardoarandah** [comment]
function SIS_Admin_Post is too intrusive. 
need to create an option screen to enable/disable it

```
add_action( 'plugins_loaded', 'init_sis' );
function init_sis() {
	if ( is_admin() ) {
		new SIS_Admin_Main();
		//TOO INTRUSIVE--> new SIS_Admin_Post();
		new SIS_Admin_Media();
	}

	new SIS_Client();
}
```

**Comment by kaiwa** [comment]
+1

**Comment by Rahe** [comment]
Hello,
Sorry for the intrusive script, I have moved it to a simple link and here is a code for disable it :
https://gist.github.com/Rahe/4538e43d37dd6e81bed86fc8f9b05979

This is possible from the 3.1.1 version.

**Comment by StaggerLeee** [comment]
It shows in options page - ACF Custom image field.
Do you maybe have some handy snippet for that ?
