### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by jezzdk** [Rahe/Simple-image-sizes#39]
Nothing happens when I click the buttons on the media settings page.

Wordpress version 4.5.3
Chrome 51.0.2704.103
Mac OS X El Capitan

**Comment by Rahe** [comment]
Hello,
It seems to be a javascript error, can you open your inspector and check if there is any JS error ?

**Comment by jezzdk** [comment]
I looked and there's no errors. Funny thing is, it worked one time when clicking the "Get the PHP for the theme" button, but now its not working anymore.

**Comment by SvenSlijkoord** [comment]
I think there is a conflict with the "Regenerate Thumbnails" plugin. After I deactivated that plugin, the buttons started working.
