### ISSUE TITLE
Not compatible with ManageWP / multisite installations

### ISSUE THREAD

**Issue by jonasskafte** [Rahe/Simple-image-sizes#41]
Hi there,

Firstly, thanks for providing such a great plugin to the WP community!

I think I've discovered a bug. As I started using ManageWP I found that one of my websites couldn't sync and after going back and fourth with the support team at ManageWP we found out that the issue had to do with the Simple Image Sizes plugin. Here's the error message I got from ManageWP:

`Class 'SIS_Admin_Main' not found occurred in wp-content/plugins/simple-image-sizes/simple_image_sizes.php on line 56. Please make sure that your website is accessible.`

You might not find it important to have the plugin compatible with ManageWP, and fair enough if so, but I just thought I would flag it here as it seems a shame to not be able to use these two great tools in the same time (all other plugins I've installed throughout my 15+ sites have no problems syncing).

I would certainly contribute with a solution to this myself, if only I had the knowledge to do so.

FYI. I'm using Simple Image Sizes on a multisite installation – not sure if that's in any way relevant.

Many thanks.

**Comment by Rahe** [comment]
Hello,

Thank you for the bug report :).
I do not really understand why this cannot be functionnal, i'm including my files at ìs_admin` condition and instanciate my classes at the same condition.
My files are included before the `plugins_loaded` filter is thrown.
I have created a tweet for more informations : https://twitter.com/Raherian/status/791910158485946368

Cheers

**Comment by jonasskafte** [comment]
Hi Rahe,

Thanks for your quick response. I'm also in contact with the guys at ManageWP and they are also looking into the issue.

I'll keep you updated!

Cheers

**Comment by jonasskafte** [comment]
UPDATE:

The guys at ManageWP seems to think that this issue is related to multisite installations only and that it is _not_ an isolated problem (ref. [the tweet above](https://twitter.com/Raherian/status/791910158485946368)).

Hope adding this little piece of information is helpful somehow.

Thanks!

**Comment by jonasskafte** [comment]
Hi there,

Hope you are well.

Just writing to hear if this is an issue you can see a solution to? Sorry to bother you, but I'm about to find an alternative to Simple Image Sizes if the problem cannot be fixed.

Last time I asked ManageWP about this, this was there response:

> [...] You are right, we thought that this was an isolated issue at first, however, we discovered that the issue appears on Multisite networks while single sites are working without issues.
> 
> After that, I contacted the plugin developer directly, and I just did it again, hopefully, this will be resolved soon. [...]

So I wonder if the guys at ManageWP gave you any useful information about the issue?

Thanks again for great plugin!

All the best

**Comment by joeqsd** [comment]
As of August this is still an issue-

I received a response from LiquidWeb suggesting the following;  if you would consider making the changes in your source for future updates as well- it would be great for customers who use multi-site.

This is not an edge case as you suggest- 

Thanks


Vladimir replied | Aug 4, 13:07
-- | --
Hi Joan,Thanks for taking your time to contact us.
To be honest with you, this Simple Images Size plugin is in conflict with our ManageWP Worker plugin and that is the reason why this message is displayed in your dashboard.

What you could do is to try to edit the code of the plugin like the author of this Simple Images Size plugin suggested in this thread below.

https://wordpress.org/support/topic/two-bugs-in-the-attachment-queries-1/Or you could contact the plugin author and ask him to remove these lines for you so you could continue to use ManageWP with this plugin.

Hope I've helped a bit and please let me know if there is anything else I could assist you with.
Kindly,--Vlad

**Comment by Rahe** [comment]
Hello fellows,

I don't know why this issue appears, is that because ManageWP load the plugin in normal WP context then set the admin constants ?

So between the file load and the plugins_loaded action the context is changed ?

**Comment by jonasskafte** [comment]
Hi @Rahe,

Thanks for following up on this.

Unfortunately, I can't tell you what exactly the problem is, but I've just emailed ManageWP support and asked them to contribute to this conversation with more details about what exactly the issue is. Hopefully they'll pitch in and we can get this solved once and for all.

@joeqsd – are you by any chance better informed about why this is happening?

Thanks

**Comment by joeqsd** [comment]
Did you see the recommended changes from ManageWP?

They are recommending moving to pieces of code to a different area-


Best regards,

Joe
*Joe DiStefano*
QS Digital Solutions - COO/PMO
(800) 393-5730 Ext. 103
joseph@qs.digital

**Comment by nebojsa94** [comment]
Hey guys, ManageWP dev here, it appears that issue was on our side, @jonasskafte you can update ManageWP Worker plugin to version 4.2.22, deactivate then activate worker plugin, after that sync will work :)

**Comment by Rahe** [comment]
I'm glad this is working, i'm closing this issue ;)

**Comment by jonasskafte** [comment]
Thanks @nebojsa94! And apologies to you @Rahe – I was told that the issue was with your plugin. Anyway, good that it's now solved!

Cheers!
