### ISSUE TITLE
make it compatible with 4.7.2 possible ?

### ISSUE THREAD

**Issue by ghost** [Rahe/Simple-image-sizes#43]
Seems to be THE plugin i need for a long time... but it's seems to be buggy with 4.7.2.

- Request : possible the have the availability to not crop, keep the original ratio AND have the desired width&height (ie : having blank around the image. ex: making a 16:9 format fit in a square end format).

**Comment by vwasteels** [comment]
+1 plugin is not compatible with latest WP (4.7.3)

**Comment by crabnky** [comment]
+1 for latest

**Comment by Rahe** [comment]
Hello,

I have tested the plugin with the 4.7.3 and no problems for me.
Can you describe the processes you use to test this ?

**Comment by crabnky** [comment]
Sorry, my bad - error wasn't related to your plugin. Works great with latest WP.

**Comment by Rahe** [comment]
Cool :) I close this !
