### ISSUE TITLE
Update 3.2.0 crashed my site

### ISSUE THREAD

**Issue by GlazerGallery** [Rahe/Simple-image-sizes#47]
I installed the update and got this:
Parse error: syntax error, unexpected '[' in /data/55/4/41/66/4204229/user/4714197/htdocs/wpmain/wp-content/plugins/simple-image-sizes/classes/main.php on line 7

It crashed my site and I had to reinstall 3.1.1.

**Comment by Joqus** [comment]
Same error happened to me. I had to disabled the plugin manually to be able to use the site again. Is there a solution?

**Comment by GlazerGallery** [comment]
I updated to PHP 5.6 from PHP 5.3 and then I was able to update to 3.2.0 without a problem.

**Comment by Rahe** [comment]
Hello,

The minimum version for the plugin is 5.4, but i'm targeting 5.6 on wordpress.org.
Sorry for the inconvenience.

Rahe,

**Comment by badpenguin** [comment]
Please add a warning before activating the plugin if the PHP's version does not match.

**Comment by tlemke** [comment]
I encountered the same error with version 3.2.0 and I'm using PHP 5.6.32. When I revert to 3.1.1 and it runs fine.

**Comment by culturalproduct** [comment]
Check your PHP version first I guess. My entire site vanished, and, I lost access to the WP dashboard so couldn't disable the plugin by that method. Wasted 30 minutes of tech support finding out what happened. Removed plug in via FTP. Site and WP returned.
