### ISSUE TITLE
.git directory included in Wordpress.org release

### ISSUE THREAD

**Issue by hgrimelid** [Rahe/Simple-image-sizes#51]
I noticed that the `.git` directory and `.gitignore` file are included in the release at Wordpress.org.

This is also addressed in this [thread at Wordpress.org](https://wordpress.org/support/topic/released-version-on-org-should-not-have-git/).

Any chance these can be removed from upcoming versions?

**Comment by Rahe** [comment]
Hello,

Yes, this is an unfortunate issue from the last version and the usage of an automated script for creating the package from github.

This also have already been reported on wp.org, thank you for your issue

Rahe,

**Comment by carl-alberto** [comment]
Hi @Rahe, nice plugin you have here and sorry for double posting this issue around in the forums in here: https://wordpress.org/support/topic/is-it-possible-to-delete-the-git-folder-and-gitignore-in-the-plugin-code/

Looking forward for the next version to not have the not needed files in the plugin operation when installed like the .gitignore, .git, composer.json and gulpfile.js. I can help you out in automating your plugin release process so it will be cleaner for each release :)

Thanks and more power to your plugin!

**Comment by Rahe** [comment]
Hello,

Sorry for the very long response time for a very tiny edit.
The 3.2.1 is without .git folder on the repository :)

Nicolas

**Comment by carl-alberto** [comment]
Thank you very much @Rahe !
