### ISSUE TITLE
Completely delete plugin

### ISSUE THREAD

**Issue by sjjensen** [Rahe/simple-image-sizes#61]
I used the plugin to make a few custom image sizes and it worked great. Then I made some design changes to my theme and no longer needed the plugin and the extra image sizes. 

Despite deleting the plugin, the custom image sizes are still being generated. My functions.php file doesn't have any add_image_size commands, so the plugin is still affecting my site even though it's deleted. How do I completely remove the plugin's influence in the database?

<img width="537" alt="Screen Shot 2020-04-18 at 9 24 18 AM" src="https://user-images.githubusercontent.com/16997646/79643200-b90c8f00-8156-11ea-8ea7-bd29c470c47f.png">

**Comment by anjop** [comment]
I have the same problem! After changing the theme and without the plugin the before added sizes are still generated. When I install and activate the plugin to delete the custom images sizes, they disappear but again appear in the settings as soon as I click on save changes.

I can't find any add_image_size commands anywhere, can't find any information about this plugin in the options.php or elsewhere in the database. 

So somehow the plugin influences still and can't be totally deleted! Very frustrating!

Is there any idea how to get rid of this false settings? This would be very helpful!
Thanks a lot!

**Comment by iamwebrocker** [comment]
Hi, have a look in the database, in the [wp]_options table. in my install, there is an entry with option_name "custom_image_sizes" which has a serialized string with the custom image sizes set by the simple-image-size settings.
I think if you delete this entry, WP will fall back to the standard sizes. But, make a db backup first ;-)

**Comment by Rahe** [comment]
Hello,

This is a really weird behaviour, as soon as the plugin is deactivated, the "add_image_size" function is not called anymore.
There is no "custom_image_sizes" option handled by WordPress.

How do you display this list ? Another plugin ?

**Comment by anjop** [comment]
Yes it is weird!
When I deactivate the plugin in Media Settings no additional sizes are shown.
When I use a simple plugin "regenerate thumbnails" the additional sizes are still used.
When I activate the plugin the additional sizes are still there. When I try to delete them they seem to be gone, but as soon as I press "save settings" they come again as before.
Once I found "custom_image_sizes" in the [wp]_options table and there deleted the additional sizes. But there was only one of them and in the plugin all three still stayed visible only with out "size" in the field.
Please, how to get rid of the whole settings of this plugin, which once was very helpful, but now only creates problems.
THANKS!

**Comment by Rahe** [comment]
Hello,

I understand, next version will delete the option from the options when the plugin is deleted by WordPress interface.

**Comment by anjop** [comment]
That#s good news, if there will be a new version updated to wp 5! I now use a different plugin for generating thumbnails which still shows the custom images sizes, although the plugin is deleted and in the DB I deleted the custom_image_size field.  I attach a screenshot to show you what the other plugin shows me.
![Bildschirmfoto 2020-11-12 um 16 09 46](https://user-images.githubusercontent.com/25871555/98958627-c201eb00-2502-11eb-864d-f54619466b8a.png)

**Comment by iamwebrocker** [comment]
@anjop
those three size in your screenshot, I don't think they actually are from Simple Image Size, but from the (newer) WordPress.
I have exactly the same sizes in my install - and "my" custom sizes are those with the "wbr-" suffix:
![Bildschirmfoto 2020-11-12 um 20 51 38](https://user-images.githubusercontent.com/1223080/98989338-423b4700-2529-11eb-9380-3bda14d73de2.png)
As you can see in the screen attached, "medium_large", 1536x1536 and 2048x2048 are present in my install, too.

**Comment by anjop** [comment]
THANKS a lot for your research!
The strange thing is, that these three sizes don't appear in the Settings / Media! only when "simple_image_size" is activated then you see them in Settings / media.
This is really confusing!

**Comment by iamwebrocker** [comment]
_:This is really confusing!_
Yes it is - but this seems to be a intended behaviour by the WordPress UI - as I understand it, these sizes are intentionally hidden from the users, since they should not be altered freely (like the other three sizes). Since Simple Image Size extends the media-options page in the backend, it somehow unveils these hidden image sizes, because they are registered.
@Rahe maybe you could skip these and/or exclude them from the "delete"? or add some info text regarding these special/built-in sizes?

**Comment by anjop** [comment]
@Rahe!
It seams that now some mysteries about your nice plugin and the new features of WP are more clear! I still not understand why WP creates those image sizes, which then are hidden. But anyway, knowing this, makes your plugin again more interesting!
So it really would be wonderful, if you could please update your plugin and test it with the actual wp version. The above by iamwebrocker mentioned ideas would be great to do! 
So when searching for your plugin there wouldn't be any more the information, that it is old and not tested.
Thanks for all your effort and engagement!

**Comment by Rahe** [comment]
Hello,

I'll try to handle this but it's difficult to detect my sizes and the natives/theme ones.
Because I allow to change every other sizes, the delete button can maybe changed to "Reset".
Anyway, the option value issue will be solved in next version.
