### ISSUE TITLE
Screenshots in Github description not showing up

### ISSUE THREAD

**Issue by Julix91** [Rahe/simple-image-sizes#62]
Example:

https://camo.githubusercontent.com/f9fd65e8a411b078b44958aefad2e08c7b28001c/687474703a2f2f732e776f726470726573732e6f72672f657874656e642f706c7567696e732f73696d706c652d696d6167652d73697a65732f73637265656e73686f742d312e706e67

Returns `Error Fetching Resource`

<img width="585" alt="Screen Shot 2020-04-23 at 9 39 33 AM" src="https://user-images.githubusercontent.com/12877287/80125316-5cd6b000-8546-11ea-90fc-ea2b89ddd167.png">

**Comment by Klemart3D** [comment]
I have created a PR for this : #63

**Comment by Rahe** [comment]
PR merged, thank you 😄
