### ISSUE TITLE
Fatal Error after install (Wordpress 5.8)

### ISSUE THREAD

**Issue by FabioII** [Rahe/simple-image-sizes#70]
I installed the plugin and got this:

Fatal error: Uncaught Error: Class 'Rahe\Simple_Image_Sizes\Main' not found in /homepages/16/d70121854/htdocs/clickandbuilds/KuberBauGmbH/wp-content/plugins/simple-image-sizes-master/simple_image_sizes.php:42 Stack trace: #0 /homepages/16/d70121854/htdocs/clickandbuilds/KuberBauGmbH/wp-includes/class-wp-hook.php(303): init_sis('') #1 /homepages/16/d70121854/htdocs/clickandbuilds/KuberBauGmbH/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #2 /homepages/16/d70121854/htdocs/clickandbuilds/KuberBauGmbH/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #3 /homepages/16/d70121854/htdocs/clickandbuilds/KuberBauGmbH/wp-settings.php(441): do_action('plugins_loaded') #4 /homepages/16/d70121854/htdocs/clickandbuilds/KuberBauGmbH/wp-config.php(87): require_once('/homepages/16/d...') #5 /homepages/16/d70121854/htdocs/clickandbuilds/KuberBauGmbH/wp-load.php(50): require_once('/homepages/16/d...') #6 /homepages/16/d70121854/htdocs/clickandbuilds/KuberBauGmbH/wp-admin/admin.php(34): require_once('/homepages/ in /homepages/16/d70121854/htdocs/clickandbuilds/KuberBauGmbH/wp-content/plugins/simple-image-sizes-master/simple_image_sizes.php on line 42

I don't need any help. This is for information only. The plugin was installed on a test site

**Comment by Rahe** [comment]
Hi, thank you for the report :)
