### ISSUE TITLE
Update to show as "Tested up to: 5.9.1" on WP ORG

### ISSUE THREAD

**Issue by deafjoe** [Rahe/simple-image-sizes#71]
Please update/test so that Plugin shows as "Compatible up to: 5.9.1" in wordpress.org.
My security software (WordFence) reports that the plugin "appears to have been abandoned" as it hasn't changed for 3 years.
Still using this great plugin of yours.

**Comment by Rahe** [comment]
Hello,

Plugin have been updated :)

Nicolas,

**Comment by deafjoe** [comment]
Thanks.
